# Generated by Django 5.2 on 2025-11-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perjalanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('tgl_berangkat', models.DateField()),
                ('tgl_kembali', models.DateField()),
                ('harga', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('jumlah_orang', models.IntegerField()),
                ('tgl_pemesanan', models.DateTimeField(auto_now_add=True)),
                ('total_harga', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('perjalanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemesanan', to='travel.perjalanan')),
            ],
        ),
        migrations.CreateModel(
            name='Ulasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengulas', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('komentar', models.TextField(blank=True, null=True)),
                ('tgl_ulasan', models.DateTimeField(auto_now_add=True)),
                ('perjalanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulasan', to='travel.perjalanan')),
            ],
        ),
    ]
